context:
  name: lamindb_setup
  version: 1.6.1
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lamindb_setup-${{ version }}.tar.gz
  sha256: 43f5aed335c65f717b9098b33c695c1f66a84621620e397516ddaa154e9c3772

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - lamin_utils >=0.3.3
    - django >=5.1,<5.2
    - dj-database-url >=1.3.0,<3.0.0
    - pydantic-settings
    - appdirs <2.0.0
    - requests
    - universal_pathlib ==0.2.6
    - botocore <2.0.0
    - supabase >=2.8.1,<=2.15.0
    - gotrue <=2.12.0
    - pyjwt <3.0.0
    - psutil
    - packaging
    - click

tests:
  - python:
      imports:
        - lamindb_setup
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Setup & configure LaminDB.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/laminlabs/lamindb-setup

extra:
  recipe-maintainers:
    - hadim
